apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-addresspool
  namespace: metallb-system
spec:
  addresses:
  - 172.28.62.192-172.28.62.202 # This is a range on your local network which is outside of your DHCP range
  autoAssign: true
  avoidBuggyIPs: false