---
apiVersion: v1
kind: Service
metadata:
  name: mysite-service
  namespace: development
spec:
  selector:
    app: mysite-service
  ports:
    - port: 80
      targetPort: 80 # This is the port of the service inside the pod / container
  type: LoadBalancer

